#!/usr/bin/env python
"""Fit a latent multiplicative model for ShipClass fire-control tables.

The model assumes every fire-control table cell is generated from the observed
left-top cell of the same battery:

    observed = round(left_top * aspect_factor * range_band_factor * speed_factor)

The fitted factors help check whether the table internals are generated by a
small set of multipliers rather than independent values.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
import sys

try:
    import numpy as np
    import pandas as pd
    from scipy.optimize import differential_evolution, minimize
except ImportError as exc:
    print(
        "Missing Python analysis dependency. Install with:\n"
        "  python -m pip install --user numpy pandas scipy",
        file=sys.stderr,
    )
    raise SystemExit(2) from exc

import analyze_shipclass_fire_control as ship_fc


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SHIPCLASSES = REPO_ROOT / "Assets" / "StreamingAssets" / "Scenarios" / "ShipClasses.xml"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "Tools" / "shipclass_fire_control_analysis"

BANDS = ["Short", "Medium", "Long", "Extreme"]
ASPECTS = ["Broad", "Narrow"]
SPEEDS = [9.0, 18.0, 27.0, 36.0, 45.0]
BAND_INDEX = {band: idx for idx, band in enumerate(BANDS)}
ASPECT_INDEX = {aspect: idx for idx, aspect in enumerate(ASPECTS)}
SPEED_INDEX = {speed: idx for idx, speed in enumerate(SPEEDS)}
FIRE_CONTROL_CELLS = [
    ("Short", "Broad", "shortBroad"),
    ("Short", "Narrow", "shortNarrow"),
    ("Medium", "Broad", "mediumBroad"),
    ("Medium", "Narrow", "mediumNarrow"),
    ("Long", "Broad", "longBroad"),
    ("Long", "Narrow", "longNarrow"),
    ("Extreme", "Broad", "extremeBroad"),
    ("Extreme", "Narrow", "extremeNarrow"),
]


def round_half_up(values: np.ndarray) -> np.ndarray:
    return np.floor(values + 0.5)


def extract_cells(shipclasses_path: Path) -> pd.DataFrame:
    root = ship_fc.read_xml_root(shipclasses_path)
    rows: list[dict[str, object]] = []
    battery_id = 0

    for ship_class in root.findall("ShipClass"):
        ship_name = (ship_class.findtext("name/english") or "").strip()
        ship_type = (ship_class.findtext("type") or "").strip()
        country = (ship_class.findtext("country") or "").strip()

        for battery in ship_class.findall("batteryRecords/BatteryRecord"):
            records = battery.findall("fireControlTableRecords/FireControlTableRecord")
            if not records:
                continue

            left_top = None
            for record in records:
                speed = ship_fc.parse_float(record.findtext("speedThresholdKnot"))
                if speed == 9.0:
                    left_top = ship_fc.parse_float(record.findtext("shortBroad"))
                    break
            if left_top is None:
                continue

            battery_name = (battery.findtext("name/english") or "").strip()
            code = (battery.findtext("fireControlType/code") or "").strip()
            range_yards = ship_fc.parse_float(battery.findtext("rangeYards"))
            shell_size = ship_fc.parse_float(battery.findtext("shellSizeInch"))
            rate_of_fire = ship_fc.parse_float(battery.findtext("maxRateOfFireShootPerMin"))
            damage_rating = ship_fc.parse_float(battery.findtext("damageRating"))

            for record in records:
                speed = ship_fc.parse_float(record.findtext("speedThresholdKnot"))
                if speed not in SPEED_INDEX:
                    continue

                for range_band, aspect, tag in FIRE_CONTROL_CELLS:
                    rows.append(
                        {
                            "battery_id": battery_id,
                            "ship_name": ship_name,
                            "ship_type": ship_type,
                            "country": country,
                            "battery_name": battery_name,
                            "code": code,
                            "left_top_value": left_top,
                            "range_band": range_band,
                            "range_band_index": BAND_INDEX[range_band],
                            "aspect": aspect,
                            "aspect_index": ASPECT_INDEX[aspect],
                            "speed_threshold_knot": speed,
                            "speed_index": SPEED_INDEX[speed],
                            "fire_control_value": ship_fc.parse_float(record.findtext(tag)),
                            "range_yards": range_yards,
                            "shell_size_inch": shell_size,
                            "rate_of_fire": rate_of_fire,
                            "damage_rating": damage_rating,
                        }
                    )

            battery_id += 1

    df = pd.DataFrame(rows)
    if df.empty:
        raise ValueError(f"No fire-control cells were extracted from {shipclasses_path}")
    return df


def unpack_params(params: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    aspect = np.array([1.0, params[0]])
    range_band = np.array([1.0, params[1], params[2], params[3]])
    speed = np.array([1.0, params[4], params[5], params[6], params[7]])
    return aspect, range_band, speed


def latent_values(df: pd.DataFrame, params: np.ndarray) -> np.ndarray:
    aspect, range_band, speed = unpack_params(params)
    return (
        df["left_top_value"].to_numpy(dtype=float)
        * aspect[df["aspect_index"].to_numpy(dtype=int)]
        * range_band[df["range_band_index"].to_numpy(dtype=int)]
        * speed[df["speed_index"].to_numpy(dtype=int)]
    )


def predict_values(df: pd.DataFrame, params: np.ndarray) -> np.ndarray:
    return round_half_up(latent_values(df, params))


def objective(df: pd.DataFrame, params: np.ndarray, metric: str) -> float:
    aspect, range_band, speed = unpack_params(params)
    penalty = 0.0
    penalty += 100.0 * sum(max(0.0, range_band[idx + 1] - range_band[idx]) for idx in range(3))
    penalty += 100.0 * sum(max(0.0, speed[idx + 1] - speed[idx]) for idx in range(4))
    if not 0.0 <= aspect[1] <= 1.0:
        penalty += 100.0

    observed = df["fire_control_value"].to_numpy(dtype=float)
    predicted = predict_values(df, params)
    residual = predicted - observed
    if metric == "sse":
        loss = float(np.mean(residual * residual))
    else:
        loss = float(np.mean(np.abs(residual)))
    return loss + penalty


def fit_model(df: pd.DataFrame, seed: int, metric: str) -> np.ndarray:
    bounds = [
        (0.35, 0.90),  # Narrow
        (0.30, 0.95),  # Medium
        (0.15, 0.85),  # Long
        (0.00, 0.75),  # Extreme
        (0.35, 0.95),  # 18 kt
        (0.20, 0.90),  # 27 kt
        (0.10, 0.85),  # 36 kt
        (0.00, 0.80),  # 45 kt
    ]

    result = differential_evolution(
        lambda params: objective(df, params, metric),
        bounds,
        tol=1e-8,
        seed=seed,
        polish=True,
        workers=1,
        maxiter=1000,
        popsize=25,
    )
    refined = minimize(
        lambda params: objective(df, params, metric),
        result.x,
        method="Nelder-Mead",
        options={"maxiter": 20000, "xatol": 1e-10, "fatol": 1e-10},
    )
    return refined.x if refined.fun <= result.fun else result.x


def build_result_frame(df: pd.DataFrame, params: np.ndarray) -> pd.DataFrame:
    result = df.copy()
    result["latent_fire_control_value"] = latent_values(result, params)
    result["predicted_fire_control_value"] = predict_values(result, params)
    result["residual"] = result["predicted_fire_control_value"] - result["fire_control_value"]
    result["absolute_residual"] = result["residual"].abs()
    return result


def score(result: pd.DataFrame) -> dict[str, float]:
    residual = result["residual"].to_numpy(dtype=float)
    return {
        "cells": float(len(result)),
        "batteries": float(result["battery_id"].nunique()),
        "exact": float(np.mean(residual == 0)),
        "mae": float(np.mean(np.abs(residual))),
        "rmse": float(math.sqrt(np.mean(residual * residual))),
        "max_abs_error": float(np.max(np.abs(residual))),
        "within_one": float(np.mean(np.abs(residual) <= 1)),
    }


def dimension_summary(result: pd.DataFrame, dimension: str) -> pd.DataFrame:
    return (
        result.groupby(dimension, dropna=False)
        .agg(
            cells=("residual", "size"),
            exact=("residual", lambda s: float(np.mean(s == 0))),
            mae=("absolute_residual", "mean"),
            bias=("residual", "mean"),
            max_abs_error=("absolute_residual", "max"),
        )
        .reset_index()
    )


def factor_frames(params: np.ndarray) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    aspect, range_band, speed = unpack_params(params)
    aspect_df = pd.DataFrame({"aspect": ASPECTS, "factor": aspect})
    range_df = pd.DataFrame({"range_band": BANDS, "factor": range_band})
    speed_df = pd.DataFrame({"speed_threshold_knot": SPEEDS, "factor": speed})
    return aspect_df, range_df, speed_df


def print_factor_table(title: str, df: pd.DataFrame) -> None:
    print(f"\n{title}")
    print("-" * len(title))
    print(df.round({"factor": 4}).to_string(index=False))


def print_score(stats: dict[str, float]) -> None:
    print(
        f"cells={int(stats['cells'])} batteries={int(stats['batteries'])} "
        f"exact={stats['exact']:.4f} MAE={stats['mae']:.4f} "
        f"RMSE={stats['rmse']:.4f} max_abs_error={stats['max_abs_error']:.0f} "
        f"within_one={stats['within_one']:.4f}"
    )


def write_outputs(
    output_dir: Path,
    result: pd.DataFrame,
    aspect_df: pd.DataFrame,
    range_df: pd.DataFrame,
    speed_df: pd.DataFrame,
    summaries: dict[str, pd.DataFrame],
    top_residuals: pd.DataFrame,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    result.to_csv(output_dir / "latent_multiplier_cell_results.csv", index=False, encoding="utf-8-sig")
    pd.concat(
        [
            aspect_df.rename(columns={"aspect": "level"}).assign(dimension="aspect"),
            range_df.rename(columns={"range_band": "level"}).assign(dimension="range_band"),
            speed_df.rename(columns={"speed_threshold_knot": "level"}).assign(dimension="speed"),
        ],
        ignore_index=True,
    )[["dimension", "level", "factor"]].to_csv(
        output_dir / "latent_multiplier_factors.csv",
        index=False,
        encoding="utf-8-sig",
    )
    for name, summary in summaries.items():
        summary.to_csv(output_dir / f"latent_multiplier_summary_by_{name}.csv", index=False, encoding="utf-8-sig")
    top_residuals.to_csv(output_dir / "latent_multiplier_top_residuals.csv", index=False, encoding="utf-8-sig")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Fit latent multipliers for ShipClass fire-control table cells.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--shipclasses", type=Path, default=DEFAULT_SHIPCLASSES)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--metric", choices=["mae", "sse"], default="mae")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--top", type=int, default=30)
    parser.add_argument("--no-write", action="store_true")
    args = parser.parse_args()

    df = extract_cells(args.shipclasses)
    params = fit_model(df, args.seed, args.metric)
    result = build_result_frame(df, params)
    aspect_df, range_df, speed_df = factor_frames(params)
    stats = score(result)

    print(f"Source: {args.shipclasses}")
    print("Model: round_half_up(left_top * aspect_factor * range_band_factor * speed_factor)")
    print(f"Fit metric: {args.metric}")
    print_score(stats)

    print_factor_table("Aspect Factors", aspect_df)
    print_factor_table("Range Band Factors", range_df)
    print_factor_table("Speed Factors", speed_df)

    summaries = {
        "aspect": dimension_summary(result, "aspect"),
        "range_band": dimension_summary(result, "range_band"),
        "speed": dimension_summary(result, "speed_threshold_knot"),
        "code": dimension_summary(result, "code"),
    }
    for name, summary in summaries.items():
        print(f"\nSummary By {name.replace('_', ' ').title()}")
        print("-" * (11 + len(name)))
        print(summary.round({"exact": 4, "mae": 4, "bias": 4}).to_string(index=False))

    top_residuals = result.sort_values(
        ["absolute_residual", "code", "ship_name", "battery_name"],
        ascending=[False, True, True, True],
    ).head(args.top)
    print(f"\nTop {args.top} Residuals")
    print("-" * (5 + len(str(args.top))))
    print(
        top_residuals[
            [
                "residual",
                "predicted_fire_control_value",
                "latent_fire_control_value",
                "fire_control_value",
                "left_top_value",
                "code",
                "speed_threshold_knot",
                "range_band",
                "aspect",
                "ship_name",
                "battery_name",
            ]
        ]
        .round({"latent_fire_control_value": 3})
        .to_string(index=False)
    )

    if not args.no_write:
        write_outputs(args.output_dir, result, aspect_df, range_df, speed_df, summaries, top_residuals)
        print(f"\nWrote CSV outputs to: {args.output_dir}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
